sudo: required
services:
  - docker

before_install:
  - docker build -t manuhazen/docker-practicing -f Dockerfile.dev .

script:
  - docker run manuhazen/docker-practicing npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-testing"
  env: "DockerTesting-env"
  bucket_name: "elasticbeanstalk-us-east-2-593147892855"
  bucket_path: "docker-testing"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
