sudo: required
services:
  - docker

before_install:
  - docker build -t manuhazen/docker-practicing -f Dockerfile.dev .

script:
  - docker run manuhazen/docker-practicing npm run test -- --coverage
