FROM node:alpine

WORKDIR '/app'

COPY package.json .
RUN yarn install

COPY . .

CMD ["yarn", "start"]


# Using Docker Volume
# docker run -p 3000:3000 -v /app/node_modules -v $(pwd):/app <image_id>
